import { DefaultTheme } from 'react-native-paper';

export const lightTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#6366f1', // Indigo
    primaryContainer: '#e0e7ff',
    secondary: '#10b981', // Emerald
    secondaryContainer: '#d1fae5',
    tertiary: '#f59e0b', // Amber
    surface: '#ffffff',
    surfaceVariant: '#f8fafc',
    background: '#ffffff',
    error: '#ef4444',
    errorContainer: '#fee2e2',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
    onSurface: '#1e293b',
    onSurfaceVariant: '#64748b',
    onBackground: '#1e293b',
    onError: '#ffffff',
    outline: '#cbd5e1',
    outlineVariant: '#e2e8f0',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#334155',
    inverseOnSurface: '#f1f5f9',
    inversePrimary: '#a5b4fc',
    // Custom colors for WhatsApp-like interface
    whatsappGreen: '#25D366',
    whatsappDarkGreen: '#128C7E',
    whatsappTeal: '#075E54',
    whatsappLight: '#DCF8C6',
    chatBubbleUser: '#6366f1',
    chatBubbleBot: '#f1f5f9',
    success: '#10b981',
    warning: '#f59e0b',
    info: '#3b82f6',
  },
  fonts: {
    ...DefaultTheme.fonts,
    displayLarge: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: -0.25,
    },
    displayMedium: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
    },
    displaySmall: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
    },
    headlineLarge: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
    },
    headlineMedium: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
    },
    headlineSmall: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
    },
    titleLarge: {
      fontFamily: 'System',
      fontWeight: '500',
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    titleMedium: {
      fontFamily: 'System',
      fontWeight: '500',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
    },
    titleSmall: {
      fontFamily: 'System',
      fontWeight: '500',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    bodyLarge: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.5,
    },
    bodyMedium: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    bodySmall: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
    },
    labelLarge: {
      fontFamily: 'System',
      fontWeight: '500',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelMedium: {
      fontFamily: 'System',
      fontWeight: '500',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    labelSmall: {
      fontFamily: 'System',
      fontWeight: '500',
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
  },
};

export const darkTheme = {
  ...lightTheme,
  dark: true,
  colors: {
    ...lightTheme.colors,
    primary: '#818cf8',
    primaryContainer: '#4338ca',
    secondary: '#34d399',
    secondaryContainer: '#059669',
    tertiary: '#fbbf24',
    surface: '#1e293b',
    surfaceVariant: '#334155',
    background: '#0f172a',
    error: '#f87171',
    errorContainer: '#dc2626',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
    onSurface: '#f1f5f9',
    onSurfaceVariant: '#cbd5e1',
    onBackground: '#f1f5f9',
    onError: '#ffffff',
    outline: '#64748b',
    outlineVariant: '#475569',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#f1f5f9',
    inverseOnSurface: '#334155',
    inversePrimary: '#6366f1',
    // Dark theme custom colors
    whatsappGreen: '#25D366',
    whatsappDarkGreen: '#128C7E',
    whatsappTeal: '#075E54',
    whatsappLight: '#2a2a2a',
    chatBubbleUser: '#818cf8',
    chatBubbleBot: '#334155',
    success: '#34d399',
    warning: '#fbbf24',
    info: '#60a5fa',
  },
};

// Spacing system
export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

// Component styles
export const commonStyles = {
  container: {
    flex: 1,
    backgroundColor: lightTheme.colors.background,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  padding: {
    padding: spacing.md,
  },
  paddingHorizontal: {
    paddingHorizontal: spacing.md,
  },
  paddingVertical: {
    paddingVertical: spacing.md,
  },
  margin: {
    margin: spacing.md,
  },
  marginHorizontal: {
    marginHorizontal: spacing.md,
  },
  marginVertical: {
    marginVertical: spacing.md,
  },
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 3,
  },
  button: {
    borderRadius: 8,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  input: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: lightTheme.colors.outline,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: 16,
  },
  headerStyle: {
    backgroundColor: lightTheme.colors.primary,
    elevation: 4,
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowColor: '#000',
    shadowOffset: { height: 0, width: 0 },
  },
  headerTitleStyle: {
    color: lightTheme.colors.onPrimary,
    fontSize: 18,
    fontWeight: '600',
  },
}; 5,
  },
  card: {
    backgroundColor: lightTheme.colors.surface,
    borderRadius: 12,
    padding: spacing.md,
    marginVertical: spacing.sm,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: